{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dotnet-react-dapr-2022-06-01t21-13-26-frontend.serviceAccountName" . }}
  labels:
    {{- include "dotnet-react-dapr-2022-06-01t21-13-26-frontend.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
